### ISSUE TITLE
Many unique crew need the constraint “max 1 Selections in Force” option “And all child selections” to be checked.

### ISSUE THREAD

**Issue by ejasiunas** [BSData/world-of-tanks-miniatures-game#10]
Many unique crew need the constraint “max 1 Selections in Force” option “And all child selections” to be checked.
Unique crew without this option can be assigned to multiple vehicles.

![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/b20c03b5-d730-4d94-87bd-3e94769c11d8)

The following crew do not have this option set:

Aaron Meyrick
Abel Smythe
Albrecht Dahl
Andreas Hartman
Andrew Hetfield
Andrey Habibulin
Edwin Crane
Erwin Prentzel
Farley Cornell
Hans Baltzer
Makar Ushakov
Michael Hanneman
Mikhail Travkin
Miles O'Connell
Nikita Ovsyanniko
Nikolay Fedchenko
Quinn Kennell
Reuben Manyweather
Robert Bloch
Sergey Merinov
Seth Douglas
Viktor Possinger
Wayne Turvey
Wilhelm Lindemann
Yaroslav Abdulov

**Comment by patrickpatrickxwing** [comment]
Only Aaron was missing max 1 selection in force.  Updated.

**Comment by ejasiunas** [comment]
Sorry.  Maybe I wasn't clear or I'm mistaken about unique crew assignments.

These are the constraint settings for Aaron Meyrick and Cayden Tole, both unique crew.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/4a1c67c7-5e6e-4c66-9541-5d0a2e3aeccf)
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/c1cce0cb-8099-4299-8035-fae53e867738)

If I assign both these crew to two tanks only Cayden displays a message about being assigned multiple tanks.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/95d751f0-b88f-4547-a7d6-336831e6b4d1)

If I check the option "And all child selections" for Aaron, then assigning him also displays a message.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/73084ec5-724b-4f4a-a65a-6c10c36ad599)

![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/198587f9-232e-4d7f-a90a-88b8adbfc0e6)
