### ISSUE TITLE
Andreas Hartman “Selection Entry” type is set as a Unit, should be Upgrade.

### ISSUE THREAD

**Issue by ejasiunas** [BSData/world-of-tanks-miniatures-game#11]
Andreas Hartman “Selection Entry” type is set as a Unit, should be Upgrade.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/6f371eb0-4e3a-461b-81e2-6e13e348b5ac)

**Comment by patrickpatrickxwing** [comment]
updated

**Comment by ejasiunas** [comment]
Thanks for the quick fix.
