### ISSUE TITLE
Profile names don't match Unit (tank) names.

### ISSUE THREAD

**Issue by ejasiunas** [BSData/world-of-tanks-miniatures-game#12]
Profile names don't match Unit (tank) names.

Achilies has two profiles named Archer.
I didn't see it cause errors, but should be consistent with parent unit (tank).

![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/07efb394-4254-45cf-9293-d35834034143)

Centurion has a profile named Cromwell.
I didn't see it cause errors, but should be consistent with parent unit (tank).
(Should the Tank name be Centurion MK I, or name the profiles just Centurion?)

![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/e7826df1-d2c7-4408-9897-e8bc64ae39ef)

**Comment by patrickpatrickxwing** [comment]
updated

**Comment by ejasiunas** [comment]
Thanks for the quick fix.
