### ISSUE TITLE
Duplicate crew slots on many tanks.

### ISSUE THREAD

**Issue by ejasiunas** [BSData/world-of-tanks-miniatures-game#13]
Duplicate crew slots on many tanks.

Jagdtiger has 2 Loader slots.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/5023063e-70a8-404a-b43e-c715480157e5)

Challenger has 2 Loader slots
Churchill I has 2 Gunner slots
Hummel has 2 Loader slots
ISU-152 has 2 Loader slots
Jagdtiger has 2 Loader slots
M3 Lee has 2 Gunner slots
M7 Priest has 2 Loader slots
Maus has 2 Loader slots
Sexton 2 has 2 Loader slots
T29 has 2 Loader slots

**Comment by patrickpatrickxwing** [comment]
Please read each tank card.  Some have duplicate crew slots.  None of these tanks are incorrect.

**Comment by ejasiunas** [comment]
My bad :(
I didn't have access to all the tank cards. 
I did manage to look them up online and I see.
