### ISSUE TITLE
Categorize Tanks by Nationality

### ISSUE THREAD

**Issue by ejasiunas** [BSData/world-of-tanks-miniatures-game#14]
**Categorize Tanks by Nationality**
As the number of tanks in the game increases it becomes tedious to build lists by nationality.

**World.of.Tanks.Miniatures.gstz**

1.  Create Category Entries: Germany, Soviet Union, United Kingdom, United States
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/96b32a2f-f1b5-4454-b160-dfcafebf1d3c)

2.  Create category links under the Platoon Force Entry to the Category Entries.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/bbb1ab57-6ce2-4377-b92e-fa30b23c4b0a)

**Platoon.catz**

3.  In the Root Selection Entries of the Platoon catalog, 
change the category of each unit from Tanks to the appropriate nationality and 
check Primary option.
![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/435c2ee6-ef54-4384-b89b-9377fce27b3f)

**Comment by patrickpatrickxwing** [comment]
I appreciate your input, but this is how it was constructed.  It will remain as is.

**Comment by ejasiunas** [comment]
Thanks for considering the enhancement and your quick support.
