### ISSUE TITLE
Nashorn has Nationality of UK

### ISSUE THREAD

**Issue by ejasiunas** [BSData/world-of-tanks-miniatures-game#15]
Nashorn has Nationality of UK. Should be German.

![image](https://github.com/BSData/world-of-tanks-miniatures-game/assets/18350367/caf93182-41a8-4796-a75e-d4a285606a5d)

**Comment by patrickpatrickxwing** [comment]
updated to german

**Comment by ejasiunas** [comment]
Thanks for the quick fix.
