### ISSUE TITLE
There are some new tanks missing

### ISSUE THREAD

**Issue by TARLoki** [BSData/world-of-tanks-miniatures-game#9]
Hello,

I bought last week the new starter kit of WoT Tabletop.
There are 4 new tanks in that I miss at your app.
I want to add them to your list, but I can't, so I did a photo of the tank cards an enclosed them to this post.
I hope you can add them soon to your app.
Maybe it will also be agreat thing, If you can tell me, how I can do this by my own.

Greetings,
Sven
![20230928_124915](https://github.com/BSData/world-of-tanks-miniatures-game/assets/101013581/d272e370-1319-4777-9c24-46ca8a9745e1)
![20230928_125046](https://github.com/BSData/world-of-tanks-miniatures-game/assets/101013581/76c543fc-f313-447a-a177-8acd5e74b05f)

**Comment by patrickpatrickxwing** [comment]
Uploaded the new tanks.  May take 24 hours to filter to app and software.
